// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChoXTL_aBJX6CDyniiAc1UR26MNIhdBqc',
    appId: '1:1097189893918:web:c2d22911dc98aba1030b0f',
    messagingSenderId: '1097189893918',
    projectId: 'economic-e3c75',
    authDomain: 'economic-e3c75.firebaseapp.com',
    storageBucket: 'economic-e3c75.appspot.com',
    measurementId: 'G-Y4MEP4X04T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWNInY_qobenMFQxNzLHI5GhH9zSkfoZY',
    appId: '1:1097189893918:android:a58f9c96eef95ce7030b0f',
    messagingSenderId: '1097189893918',
    projectId: 'economic-e3c75',
    storageBucket: 'economic-e3c75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW76_r6sSEEmpu2QaFRlocbagCQuP3Cz0',
    appId: '1:1097189893918:ios:ec3bc80afe7bd876030b0f',
    messagingSenderId: '1097189893918',
    projectId: 'economic-e3c75',
    storageBucket: 'economic-e3c75.appspot.com',
    iosBundleId: 'com.example.user',
  );
}
